CREATE TABLE district_list (
    id INT AUTO_INCREMENT PRIMARY KEY,
    district_name VARCHAR(255) NOT NULL
);

INSERT INTO district_list (district_name) VALUES
('Aliağa'),
('Balçova'),
('Bayındır'),
('Bayraklı'),
('Bergama'),
('Beydağ'),
('Bornova'),
('Buca'),
('Çeşme'),
('Çiğli'), 
('Dikili'),
('Foça'),
('Gaziemir'),
('Güzelbahçe'),
('Karabağlar'),
('Karaburun'),
('Karşıyaka'),
('Kemalpaşa'),
('Kınık'),
('Kiraz'),
('Konak'),
('Menderes'),
('Menemen'),
('Narlıdere'),
('Ödemiş'),
('Seferihisar'),
('Selçuk'),
('Tire'),
('Torbalı'),
('Urla');
